language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

before_script:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpcs -p --standard=.phpcs-rules.xml . --ignore=/PHPExcel/